name: Build EXE and MAC

on:
  push:
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller beautifulsoup4

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed --clean --name SilenceDealerFinder app.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SilenceDealerFinder-Windows
          path: dist/SilenceDealerFinder.exe


  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller beautifulsoup4

      - name: Build Mac App
        run: |
          pyinstaller --onefile --windowed --clean --name SilenceDealerFinder app.py

      - name: Upload Mac build
        uses: actions/upload-artifact@v4
        with:
          name: SilenceDealerFinder-Mac
          path: dist/SilenceDealerFinder
